<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ImagenSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('imagenes')->insertOrIgnore([
            ['id' => 1, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605164/productos/q18kypcehjfsyfrcdmsk.webp', 'public_id' => 'productos/q18kypcehjfsyfrcdmsk', 'es_principal' => 1, 'producto_id' => 11],
            ['id' => 2, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605166/productos/heyvpd6nh8fehbc663my.webp', 'public_id' => 'productos/heyvpd6nh8fehbc663my', 'es_principal' => 0, 'producto_id' => 11],
            ['id' => 3, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605167/productos/vzpfsrzud2psciuwvxmr.webp', 'public_id' => 'productos/vzpfsrzud2psciuwvxmr', 'es_principal' => 0, 'producto_id' => 11],
            ['id' => 4, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605168/productos/ldfbiwmoxjifbjcb3qm8.webp', 'public_id' => 'productos/ldfbiwmoxjifbjcb3qm8', 'es_principal' => 0, 'producto_id' => 11],
            ['id' => 5, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605169/productos/rikvooseyoueqwwnfjzh.webp', 'public_id' => 'productos/rikvooseyoueqwwnfjzh', 'es_principal' => 0, 'producto_id' => 11],
            ['id' => 6, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605201/productos/qsu4kpbllezvfzgsqx88.webp', 'public_id' => 'productos/qsu4kpbllezvfzgsqx88', 'es_principal' => 1, 'producto_id' => 12],
            ['id' => 7, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605202/productos/ktbsedfpcwraywwlflhr.webp', 'public_id' => 'productos/ktbsedfpcwraywwlflhr', 'es_principal' => 0, 'producto_id' => 12],
            ['id' => 8, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605275/productos/wetj8tirr2wpiy5kmvoy.webp', 'public_id' => 'productos/wetj8tirr2wpiy5kmvoy', 'es_principal' => 1, 'producto_id' => 9],
            ['id' => 9, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605276/productos/vovki52fzta2uumtjf6c.webp', 'public_id' => 'productos/vovki52fzta2uumtjf6c', 'es_principal' => 0, 'producto_id' => 9],
            ['id' => 10, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605313/productos/cattbicejew7bln9coxk.webp', 'public_id' => 'productos/cattbicejew7bln9coxk', 'es_principal' => 1, 'producto_id' => 13],
            ['id' => 11, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605339/productos/zvevvjkncixuad4n06fu.webp', 'public_id' => 'productos/zvevvjkncixuad4n06fu', 'es_principal' => 1, 'producto_id' => 14],
            ['id' => 12, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605341/productos/oklpkouuqe2naz9maxeu.webp', 'public_id' => 'productos/oklpkouuqe2naz9maxeu', 'es_principal' => 0, 'producto_id' => 14],
            ['id' => 13, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605378/productos/hn5s8bfyjcdsyjgsu9th.webp', 'public_id' => 'productos/hn5s8bfyjcdsyjgsu9th', 'es_principal' => 1, 'producto_id' => 15],
            ['id' => 14, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605409/productos/rjgorubhv098yvcjcgwo.webp', 'public_id' => 'productos/rjgorubhv098yvcjcgwo', 'es_principal' => 1, 'producto_id' => 16],
            ['id' => 15, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605437/productos/uv0bqukwpqhtjd1adegg.webp', 'public_id' => 'productos/uv0bqukwpqhtjd1adegg', 'es_principal' => 1, 'producto_id' => 17],
            ['id' => 16, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605438/productos/bdlk63htkpokt0imsphe.webp', 'public_id' => 'productos/bdlk63htkpokt0imsphe', 'es_principal' => 0, 'producto_id' => 17],
            ['id' => 17, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605466/productos/hy1sbfktg4btxvpy9x6h.webp', 'public_id' => 'productos/hy1sbfktg4btxvpy9x6h', 'es_principal' => 1, 'producto_id' => 18],
            ['id' => 18, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605467/productos/ys5h0protfxwwe7rjpde.webp', 'public_id' => 'productos/ys5h0protfxwwe7rjpde', 'es_principal' => 0, 'producto_id' => 18],
            ['id' => 19, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605515/productos/ornjvwnk5la7e9dzwi0g.webp', 'public_id' => 'productos/ornjvwnk5la7e9dzwi0g', 'es_principal' => 1, 'producto_id' => 19],
            ['id' => 20, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605516/productos/f3aouaqp4f71m9z1gvzq.webp', 'public_id' => 'productos/f3aouaqp4f71m9z1gvzq', 'es_principal' => 0, 'producto_id' => 19],
            ['id' => 21, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605532/productos/pmfyk95pwadpemmnc1sa.webp', 'public_id' => 'productos/pmfyk95pwadpemmnc1sa', 'es_principal' => 1, 'producto_id' => 20],
            ['id' => 22, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605570/productos/gzhihm5relkurwcz1nfo.webp', 'public_id' => 'productos/gzhihm5relkurwcz1nfo', 'es_principal' => 1, 'producto_id' => 21],
            ['id' => 23, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605571/productos/dnfcwcftfxnovluimo2h.webp', 'public_id' => 'productos/dnfcwcftfxnovluimo2h', 'es_principal' => 0, 'producto_id' => 21],
            ['id' => 24, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605572/productos/e07hnidhcb8wtfl5b6yi.webp', 'public_id' => 'productos/e07hnidhcb8wtfl5b6yi', 'es_principal' => 0, 'producto_id' => 21],
            ['id' => 25, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605597/productos/wguxz18q2zblsirvsbpi.webp', 'public_id' => 'productos/wguxz18q2zblsirvsbpi', 'es_principal' => 1, 'producto_id' => 22],
            ['id' => 26, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605598/productos/ulbz393m0wdt1cfme3dk.webp', 'public_id' => 'productos/ulbz393m0wdt1cfme3dk', 'es_principal' => 0, 'producto_id' => 22],
            ['id' => 27, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605649/productos/wqsuujfnf3o9v2esprou.webp', 'public_id' => 'productos/wqsuujfnf3o9v2esprou', 'es_principal' => 1, 'producto_id' => 23],
            ['id' => 28, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605650/productos/l4lmita0o41oc4jalfol.webp', 'public_id' => 'productos/l4lmita0o41oc4jalfol', 'es_principal' => 0, 'producto_id' => 23],
            ['id' => 29, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605679/productos/pv80lg6ryylenxis6asg.webp', 'public_id' => 'productos/pv80lg6ryylenxis6asg', 'es_principal' => 1, 'producto_id' => 26],
            ['id' => 30, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605680/productos/ksoaexvhlevpn7atc0lc.webp', 'public_id' => 'productos/ksoaexvhlevpn7atc0lc', 'es_principal' => 0, 'producto_id' => 26],
            ['id' => 31, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605724/productos/ysaaejz74a5qhriankpb.webp', 'public_id' => 'productos/ysaaejz74a5qhriankpb', 'es_principal' => 1, 'producto_id' => 27],
            ['id' => 32, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605725/productos/b6tizb0l6hgixyyktoyh.webp', 'public_id' => 'productos/b6tizb0l6hgixyyktoyh', 'es_principal' => 0, 'producto_id' => 27],
            ['id' => 33, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605726/productos/bmy8dd3iligs7qxmrckm.webp', 'public_id' => 'productos/bmy8dd3iligs7qxmrckm', 'es_principal' => 0, 'producto_id' => 27],
            ['id' => 34, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605727/productos/biagudv1ajgkxwgrnsyw.webp', 'public_id' => 'productos/biagudv1ajgkxwgrnsyw', 'es_principal' => 0, 'producto_id' => 27],
            ['id' => 35, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605728/productos/birrcng6sijmkzd92no7.webp', 'public_id' => 'productos/birrcng6sijmkzd92no7', 'es_principal' => 0, 'producto_id' => 27],
            ['id' => 36, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605770/productos/x3nndenfpvkyzuiyq4em.webp', 'public_id' => 'productos/x3nndenfpvkyzuiyq4em', 'es_principal' => 1, 'producto_id' => 28],
            ['id' => 37, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605772/productos/ucvrrhvvz1pw2gyopccw.webp', 'public_id' => 'productos/ucvrrhvvz1pw2gyopccw', 'es_principal' => 0, 'producto_id' => 28],
            ['id' => 38, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605809/productos/xpcv0edc5emdfpeeqvmq.webp', 'public_id' => 'productos/xpcv0edc5emdfpeeqvmq', 'es_principal' => 1, 'producto_id' => 29],
            ['id' => 39, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605834/productos/skinukozdl1xtnk50oxm.webp', 'public_id' => 'productos/skinukozdl1xtnk50oxm', 'es_principal' => 1, 'producto_id' => 30],
            ['id' => 40, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605835/productos/udvxvr0nlcw40axm15nw.webp', 'public_id' => 'productos/udvxvr0nlcw40axm15nw', 'es_principal' => 0, 'producto_id' => 30],
            ['id' => 41, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605836/productos/wnmjgwuvob0fyidpdrnc.webp', 'public_id' => 'productos/wnmjgwuvob0fyidpdrnc', 'es_principal' => 0, 'producto_id' => 30],
            ['id' => 42, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605885/productos/yjmekbnllgg0cgysdndx.webp', 'public_id' => 'productos/yjmekbnllgg0cgysdndx', 'es_principal' => 1, 'producto_id' => 31],
            ['id' => 43, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605911/productos/cr7lzfsx5hjdggoy4owj.webp', 'public_id' => 'productos/cr7lzfsx5hjdggoy4owj', 'es_principal' => 1, 'producto_id' => 32],
            ['id' => 44, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605912/productos/c00tetvjrodmv0c3kyud.webp', 'public_id' => 'productos/c00tetvjrodmv0c3kyud', 'es_principal' => 0, 'producto_id' => 32],
            ['id' => 45, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605934/productos/l1bf2ic9msk46fdxdur1.webp', 'public_id' => 'productos/l1bf2ic9msk46fdxdur1', 'es_principal' => 1, 'producto_id' => 33],
            ['id' => 46, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605958/productos/zkxsez1jxfic8logbxhi.webp', 'public_id' => 'productos/zkxsez1jxfic8logbxhi', 'es_principal' => 1, 'producto_id' => 34],
            ['id' => 47, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605959/productos/pdx1rw09c2sns9a7o2fj.webp', 'public_id' => 'productos/pdx1rw09c2sns9a7o2fj', 'es_principal' => 0, 'producto_id' => 34],
            ['id' => 48, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779605984/productos/x6ckppirurq9ifhxy9xc.webp', 'public_id' => 'productos/x6ckppirurq9ifhxy9xc', 'es_principal' => 1, 'producto_id' => 35],
            ['id' => 49, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779606005/productos/nuip6jqeuhtall6noryk.webp', 'public_id' => 'productos/nuip6jqeuhtall6noryk', 'es_principal' => 1, 'producto_id' => 36],
            ['id' => 50, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779606028/productos/ymvu3chzj6qyjeuyxgvm.webp', 'public_id' => 'productos/ymvu3chzj6qyjeuyxgvm', 'es_principal' => 1, 'producto_id' => 39],
            ['id' => 51, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779606030/productos/g85begmfynbovei5t8go.webp', 'public_id' => 'productos/g85begmfynbovei5t8go', 'es_principal' => 0, 'producto_id' => 39],
            ['id' => 52, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779606054/productos/oylkgrclbzmx918zw4hk.webp', 'public_id' => 'productos/oylkgrclbzmx918zw4hk', 'es_principal' => 1, 'producto_id' => 40],
            ['id' => 53, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779606055/productos/fmeegvb8ebvcz3sutezf.webp', 'public_id' => 'productos/fmeegvb8ebvcz3sutezf', 'es_principal' => 0, 'producto_id' => 40],
            ['id' => 54, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779606082/productos/uvlstr3duani9cvaezvk.webp', 'public_id' => 'productos/uvlstr3duani9cvaezvk', 'es_principal' => 1, 'producto_id' => 41],
            ['id' => 55, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779606083/productos/nzuhch10884w3ncemeoh.webp', 'public_id' => 'productos/nzuhch10884w3ncemeoh', 'es_principal' => 0, 'producto_id' => 41],
            ['id' => 56, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779606115/productos/vdwodecxmr9ddoctcj73.webp', 'public_id' => 'productos/vdwodecxmr9ddoctcj73', 'es_principal' => 1, 'producto_id' => 43],
            ['id' => 57, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779606116/productos/ddlvoohy1kqp3duuaysw.webp', 'public_id' => 'productos/ddlvoohy1kqp3duuaysw', 'es_principal' => 0, 'producto_id' => 43],
            ['id' => 58, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779606117/productos/cymjdvcdlfhcpvdcakla.webp', 'public_id' => 'productos/cymjdvcdlfhcpvdcakla', 'es_principal' => 0, 'producto_id' => 43],
            ['id' => 59, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779606118/productos/qkhippp3fehusevendx1.webp', 'public_id' => 'productos/qkhippp3fehusevendx1', 'es_principal' => 0, 'producto_id' => 43],
            ['id' => 62, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779606167/productos/b3v2sdqhy1hm7f3tek2w.webp', 'public_id' => 'productos/b3v2sdqhy1hm7f3tek2w', 'es_principal' => 1, 'producto_id' => 44],
            ['id' => 63, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779606168/productos/gopacy8i1bzzs8t12zbn.webp', 'public_id' => 'productos/gopacy8i1bzzs8t12zbn', 'es_principal' => 0, 'producto_id' => 44],
            ['id' => 64, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779606170/productos/gpuxo4pvwb9lkr9nhi1n.webp', 'public_id' => 'productos/gpuxo4pvwb9lkr9nhi1n', 'es_principal' => 0, 'producto_id' => 44],
            ['id' => 65, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779606190/productos/gxclgoknlplhbpbtqhld.webp', 'public_id' => 'productos/gxclgoknlplhbpbtqhld', 'es_principal' => 1, 'producto_id' => 45],
            ['id' => 66, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779606191/productos/l67nboz0rd7uahgaws0m.webp', 'public_id' => 'productos/l67nboz0rd7uahgaws0m', 'es_principal' => 0, 'producto_id' => 45],
            ['id' => 67, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779606211/productos/ose9lvkwuntxvlli6wqk.webp', 'public_id' => 'productos/ose9lvkwuntxvlli6wqk', 'es_principal' => 1, 'producto_id' => 46],
            ['id' => 68, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779606213/productos/i9pk788z7v9ulm6qdgos.webp', 'public_id' => 'productos/i9pk788z7v9ulm6qdgos', 'es_principal' => 0, 'producto_id' => 46],
            ['id' => 69, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779606238/productos/gfmusg1hv9oygv3qmcfy.webp', 'public_id' => 'productos/gfmusg1hv9oygv3qmcfy', 'es_principal' => 1, 'producto_id' => 47],
            ['id' => 70, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779606240/productos/louyejvs25njynrzuvhe.webp', 'public_id' => 'productos/louyejvs25njynrzuvhe', 'es_principal' => 0, 'producto_id' => 47],
            ['id' => 71, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779606266/productos/yvjvxjh6x3gitppbifco.webp', 'public_id' => 'productos/yvjvxjh6x3gitppbifco', 'es_principal' => 1, 'producto_id' => 48],
            ['id' => 72, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779606284/productos/m0wdo6xqwdjxsamib9e9.webp', 'public_id' => 'productos/m0wdo6xqwdjxsamib9e9', 'es_principal' => 1, 'producto_id' => 49],
            ['id' => 73, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779606307/productos/hdexwd77eoebnxbqu2gr.webp', 'public_id' => 'productos/hdexwd77eoebnxbqu2gr', 'es_principal' => 1, 'producto_id' => 50],
            ['id' => 74, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779606308/productos/x1r6qsuuivljpyuimltd.webp', 'public_id' => 'productos/x1r6qsuuivljpyuimltd', 'es_principal' => 0, 'producto_id' => 50],
            ['id' => 75, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779606343/productos/hcuw9fvgvgmynugkpajw.webp', 'public_id' => 'productos/hcuw9fvgvgmynugkpajw', 'es_principal' => 1, 'producto_id' => 51],
            ['id' => 76, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779606344/productos/xhx5gvolqea3ndmwup3t.webp', 'public_id' => 'productos/xhx5gvolqea3ndmwup3t', 'es_principal' => 0, 'producto_id' => 51],
            ['id' => 77, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779606345/productos/mgou7bplltazfdqb2bei.webp', 'public_id' => 'productos/mgou7bplltazfdqb2bei', 'es_principal' => 0, 'producto_id' => 51],
            ['id' => 78, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779606346/productos/iuctz2yo3xd5hp1hdyrh.webp', 'public_id' => 'productos/iuctz2yo3xd5hp1hdyrh', 'es_principal' => 0, 'producto_id' => 51],
            ['id' => 79, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779606404/productos/dju7obi2y2xnd0pqblya.webp', 'public_id' => 'productos/dju7obi2y2xnd0pqblya', 'es_principal' => 1, 'producto_id' => 7],
            ['id' => 80, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779606435/productos/isyakuhpchizkeamohgb.webp', 'public_id' => 'productos/isyakuhpchizkeamohgb', 'es_principal' => 1, 'producto_id' => 8],
            ['id' => 81, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779606436/productos/rbdpgkdy7wbgb2y4kvnc.webp', 'public_id' => 'productos/rbdpgkdy7wbgb2y4kvnc', 'es_principal' => 0, 'producto_id' => 8],
            ['id' => 82, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779606455/productos/rsqkpjrkgtua2ecmxwsx.webp', 'public_id' => 'productos/rsqkpjrkgtua2ecmxwsx', 'es_principal' => 1, 'producto_id' => 25],
            ['id' => 83, 'url' => 'https://res.cloudinary.com/dvez2cvyb/image/upload/v1779606456/productos/u7gaqxeualacdwdyt5u6.webp', 'public_id' => 'productos/u7gaqxeualacdwdyt5u6', 'es_principal' => 0, 'producto_id' => 25],
        ]);
    }
}
