<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ImagenSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('imagenes')->insert([
            [
                'id' => 9,
                'url' => '/storage/productos/XZVBlip8f6ozjdfbUd6mMWoOBYwYnAg0dzs03phu.webp',
                'es_principal' => 1,
                'producto_id' => 7,
            ],
            [
                'id' => 10,
                'url' => '/storage/productos/vNwBqWCndQRkRbmCxjdbCuRanr1BjmgGCZTiz8f0.webp',
                'es_principal' => 1,
                'producto_id' => 8,
            ],
            [
                'id' => 11,
                'url' => '/storage/productos/OpVu9qwmjIogTG1y1Xnw6WmsX5oTdoGtOKopnRa9.webp',
                'es_principal' => 0,
                'producto_id' => 8,
            ],
            [
                'id' => 12,
                'url' => '/storage/productos/TQZczBe7RPfzHaeDAcS0D8IQxrqC131f2gMUyCb1.webp',
                'es_principal' => 1,
                'producto_id' => 9,
            ],
            [
                'id' => 13,
                'url' => '/storage/productos/6719UocrQ9Qp7kkSEbUnmf7hJddwhfmC7IDzUNmy.webp',
                'es_principal' => 0,
                'producto_id' => 9,
            ],
            [
                'id' => 14,
                'url' => '/storage/productos/lUTu74YeO5tNumxc8HcrkJsKvXcXVVL7BRkDyLCs.webp',
                'es_principal' => 1,
                'producto_id' => 11,
            ],
            [
                'id' => 15,
                'url' => '/storage/productos/AWuzJozayNxnkQ7XPonku82dzDTy5Gf4CGFYF7vF.webp',
                'es_principal' => 0,
                'producto_id' => 11,
            ],
            [
                'id' => 16,
                'url' => '/storage/productos/rF4eXbgoGdEhpmazmCxdjQegySnbDI4YL4DiKcE8.webp',
                'es_principal' => 0,
                'producto_id' => 11,
            ],
            [
                'id' => 17,
                'url' => '/storage/productos/fsULShzWUs6FfBtdy7h1FdpWatJpzMzSbkWLhoDt.webp',
                'es_principal' => 0,
                'producto_id' => 11,
            ],
            [
                'id' => 18,
                'url' => '/storage/productos/d6BLVbLNydqwrpYrG5QQIBaxmzt4mEL6Z4T4faiS.webp',
                'es_principal' => 0,
                'producto_id' => 11,
            ],
            [
                'id' => 19,
                'url' => '/storage/productos/AqqRiLqvzYxf5s04slNjjkRdDGozgbsfhSbgIXvo.webp',
                'es_principal' => 1,
                'producto_id' => 12,
            ],
            [
                'id' => 20,
                'url' => '/storage/productos/Xh0nnzaDYM7NRZK5dfx430eAwTpsHVMayQVgohqg.webp',
                'es_principal' => 0,
                'producto_id' => 12,
            ],
            [
                'id' => 21,
                'url' => '/storage/productos/qYNSAZ8VBwpyrB2Ar40E55OCb9m5spn16s9ZOptK.webp',
                'es_principal' => 1,
                'producto_id' => 13,
            ],
            [
                'id' => 22,
                'url' => '/storage/productos/ptBIWkGi7BkpOWJoRvV0GWq0ogSAtMIYhGzvvE6K.webp',
                'es_principal' => 1,
                'producto_id' => 14,
            ],
            [
                'id' => 23,
                'url' => '/storage/productos/6hqLjxD1dYn05PS0z9M8Ua5honfOeysvIL3wk7L3.webp',
                'es_principal' => 0,
                'producto_id' => 14,
            ],
            [
                'id' => 24,
                'url' => '/storage/productos/6s7E7oMdDwqTpgJP9QR4dlt8JlbExjPpTsQ2WkNo.webp',
                'es_principal' => 1,
                'producto_id' => 15,
            ],
            [
                'id' => 25,
                'url' => '/storage/productos/VAotyH8HYzhCxUuGNL18MqAphYEcyif5yY3jVw5u.webp',
                'es_principal' => 1,
                'producto_id' => 16,
            ],
            [
                'id' => 26,
                'url' => '/storage/productos/Z07KMy7HCLBK8kiGvnLVeBeD7SDdFZNJGfeYy1lH.webp',
                'es_principal' => 1,
                'producto_id' => 17,
            ],
            [
                'id' => 27,
                'url' => '/storage/productos/DWrFg1z0LUHuGC1hBgtWd03jaSyCeIDqAEtBmhhd.webp',
                'es_principal' => 0,
                'producto_id' => 17,
            ],
            [
                'id' => 28,
                'url' => '/storage/productos/HXtHRmv8KnxlDfRIN11HdLP930TNZXX3UWwyIGKF.webp',
                'es_principal' => 1,
                'producto_id' => 18,
            ],
            [
                'id' => 29,
                'url' => '/storage/productos/pSvbPu8Ot2VkT4ZHyO8201889Zfv2w7reMrXFnta.webp',
                'es_principal' => 0,
                'producto_id' => 18,
            ],
            [
                'id' => 30,
                'url' => '/storage/productos/Zx6tZ2ibD8jjrLl0lAWpG05UTVPOcnwY3ROTNRnG.webp',
                'es_principal' => 1,
                'producto_id' => 19,
            ],
            [
                'id' => 31,
                'url' => '/storage/productos/eMDmuunKCrSPfwTK1fQAupd4CzFwJBC8OzLCgE28.webp',
                'es_principal' => 0,
                'producto_id' => 19,
            ],
            [
                'id' => 32,
                'url' => '/storage/productos/KetaN3Z8bsS4QAPbDWax84UyIQSf3q0Lws49uWNn.webp',
                'es_principal' => 1,
                'producto_id' => 20,
            ],
            [
                'id' => 33,
                'url' => '/storage/productos/h2KvW8ddoGM4Cxtuzf6Fh01wXBSGzfZZzvYFKULS.webp',
                'es_principal' => 1,
                'producto_id' => 21,
            ],
            [
                'id' => 34,
                'url' => '/storage/productos/001Hz2NGkVF1R8c95U6KqcKJpMwKh1nRQA3aOyZd.webp',
                'es_principal' => 0,
                'producto_id' => 21,
            ],
            [
                'id' => 35,
                'url' => '/storage/productos/7OgudNyBCiI3V4HLxXLtf4sj3EtOZghZNunOLrfh.webp',
                'es_principal' => 0,
                'producto_id' => 21,
            ],
            [
                'id' => 36,
                'url' => '/storage/productos/xsvYeDRAbbTxUCAIi6dia7iDe8K2hqnZmeoSZguy.webp',
                'es_principal' => 1,
                'producto_id' => 22,
            ],
            [
                'id' => 37,
                'url' => '/storage/productos/gA6kFchjUeWRHkgqDUqFlpbNKGWnlnlQJGPjucNX.webp',
                'es_principal' => 0,
                'producto_id' => 22,
            ],
            [
                'id' => 38,
                'url' => '/storage/productos/ABqVNMwAwaRZBH9Vv5J0OCltRBnlkiSBbxs98lS9.webp',
                'es_principal' => 1,
                'producto_id' => 23,
            ],
            [
                'id' => 39,
                'url' => '/storage/productos/uNoekiHgoTZaTqOGJGpcoSR273RADzcxgGpoWDBz.webp',
                'es_principal' => 0,
                'producto_id' => 23,
            ],
            [
                'id' => 40,
                'url' => '/storage/productos/fJs3MlX6fdMnUrASREE407Bpa84GJHx5gFnowHA9.webp',
                'es_principal' => 1,
                'producto_id' => 25,
            ],
            [
                'id' => 41,
                'url' => '/storage/productos/SS4i8LTcVs00TIDAC1R3v8huyReFfrwqz2yd0SaC.webp',
                'es_principal' => 0,
                'producto_id' => 25,
            ],
            [
                'id' => 42,
                'url' => '/storage/productos/iX1Z6PqIeTM6W6GCbOSuh70RPmDaCqHaPYwMg7de.webp',
                'es_principal' => 1,
                'producto_id' => 26,
            ],
            [
                'id' => 43,
                'url' => '/storage/productos/EEwBwpmInECgyY7402uAgMFv1eKhMFwre6vTDUH1.webp',
                'es_principal' => 0,
                'producto_id' => 26,
            ],
            [
                'id' => 44,
                'url' => '/storage/productos/WBZGwsf0pPoAaKM46rErhpskgacTLrsu7LHRyOoS.webp',
                'es_principal' => 1,
                'producto_id' => 27,
            ],
            [
                'id' => 45,
                'url' => '/storage/productos/i15NHzl5QIzDrd0863UtiY4z1SDe2X10ni4r5L0b.webp',
                'es_principal' => 0,
                'producto_id' => 27,
            ],
            [
                'id' => 46,
                'url' => '/storage/productos/cZD4k09vq9zPhcOuz6sB6yjBdWCFBK9OgWFU0daQ.webp',
                'es_principal' => 0,
                'producto_id' => 27,
            ],
            [
                'id' => 47,
                'url' => '/storage/productos/M5d5avHXSpBN4A6R36qqbk7iX0zoD6az7JzmYxr4.webp',
                'es_principal' => 0,
                'producto_id' => 27,
            ],
            [
                'id' => 48,
                'url' => '/storage/productos/NmNlItPI8vlXHPV05lsiLVcWuFrkzUO2VYL0vHL6.webp',
                'es_principal' => 0,
                'producto_id' => 27,
            ],
            [
                'id' => 49,
                'url' => '/storage/productos/eRFVcjWeSuW9X2eJMeGqy0JcEI3FKx6PXnAXTAfn.webp',
                'es_principal' => 1,
                'producto_id' => 28,
            ],
            [
                'id' => 50,
                'url' => '/storage/productos/swCd6RvWMlh5fc3DgQtsP71b4kJgrKXf2goKy8zC.webp',
                'es_principal' => 0,
                'producto_id' => 28,
            ],
            [
                'id' => 51,
                'url' => '/storage/productos/iGos5O6rNvDsooyGXWqUwvm0S7NPvHz5131F1vTS.webp',
                'es_principal' => 1,
                'producto_id' => 29,
            ],
            [
                'id' => 52,
                'url' => '/storage/productos/7BsVQBeSDrtq5hPCvKdwreHKZ4zAaqie4q6FpVJJ.webp',
                'es_principal' => 1,
                'producto_id' => 30,
            ],
            [
                'id' => 53,
                'url' => '/storage/productos/OeMBihNE15ELcBjvKU9SzufT6iT2mILiMluQspW1.webp',
                'es_principal' => 0,
                'producto_id' => 30,
            ],
            [
                'id' => 54,
                'url' => '/storage/productos/TzM6ORJTl9Ea0Ot1bZxqbKgnmwWNRNPTa0lajewW.webp',
                'es_principal' => 0,
                'producto_id' => 30,
            ],
            [
                'id' => 55,
                'url' => '/storage/productos/angV9x6bwKBgwORIoDWXYoy5Tx8G44PaxV9bm6iE.webp',
                'es_principal' => 1,
                'producto_id' => 31,
            ],
            [
                'id' => 56,
                'url' => '/storage/productos/pp7BZWnOd8KZPm5voeCMXkJfO7OgZBGTS80PA7HS.webp',
                'es_principal' => 1,
                'producto_id' => 32,
            ],
            [
                'id' => 57,
                'url' => '/storage/productos/Yr8HhQwsUkmkY1b3XohWq41dymhrGZ8VKbwp592k.webp',
                'es_principal' => 0,
                'producto_id' => 32,
            ],
            [
                'id' => 58,
                'url' => '/storage/productos/dRO00m2xz5Aj832KAJZt5GdLJE5goun07UeNHzhz.webp',
                'es_principal' => 1,
                'producto_id' => 33,
            ],
            [
                'id' => 59,
                'url' => '/storage/productos/ck7i6bNRKKOF7dN2v0kCedWxmQZZg84KtGDsH1Tm.webp',
                'es_principal' => 1,
                'producto_id' => 34,
            ],
            [
                'id' => 60,
                'url' => '/storage/productos/M9CZdyQus9PqN8UUOOhR4rwrbTvzoN7fH5F9fjPl.webp',
                'es_principal' => 0,
                'producto_id' => 34,
            ],
            [
                'id' => 61,
                'url' => '/storage/productos/ON0v9kNmcO1rQla0OKKKQksYfJ9Q5YVdRhkuVavN.webp',
                'es_principal' => 1,
                'producto_id' => 35,
            ],
            [
                'id' => 62,
                'url' => '/storage/productos/AMMxgtvXauJqx3aSuMv43Lst4aPE6auhyUNZzG8V.webp',
                'es_principal' => 1,
                'producto_id' => 36,
            ],
            [
                'id' => 66,
                'url' => '/storage/productos/GsiA3BjDoojMBqGFkgdV0jT5zVCKwLdDOqwGN2Z1.webp',
                'es_principal' => 1,
                'producto_id' => 39,
            ],
            [
                'id' => 67,
                'url' => '/storage/productos/uGvlspj055UBgYivIkCuC16t2WrgUXofssBVcM43.webp',
                'es_principal' => 0,
                'producto_id' => 39,
            ],
            [
                'id' => 68,
                'url' => '/storage/productos/N02iaUSyR49kQJyPfzInv3I9mIbF0vh0DmMKwdZ9.webp',
                'es_principal' => 1,
                'producto_id' => 40,
            ],
            [
                'id' => 69,
                'url' => '/storage/productos/wGRyhwCue6TOu7yKwxBjrGrTG3viEGimIgbmELDC.webp',
                'es_principal' => 0,
                'producto_id' => 40,
            ],
            [
                'id' => 70,
                'url' => '/storage/productos/3EvKZS8gvr7C7RFtlfC5JgGu6Mbdb53j0ykEbgh5.webp',
                'es_principal' => 1,
                'producto_id' => 41,
            ],
            [
                'id' => 71,
                'url' => '/storage/productos/8IZepzUrHGm0WoHTn7taaMqwq5ojLK3yniwPL1m5.webp',
                'es_principal' => 0,
                'producto_id' => 41,
            ],
            [
                'id' => 72,
                'url' => '/storage/productos/m2LDb3YyatKnxZYX8ePGRuDqLan2LJsB3ne9lVPd.webp',
                'es_principal' => 1,
                'producto_id' => 42,
            ],
            [
                'id' => 73,
                'url' => '/storage/productos/QRINqPqEB6bqniEibQv991h570WCbQPrqCI4p3S1.webp',
                'es_principal' => 0,
                'producto_id' => 42,
            ],
            [
                'id' => 74,
                'url' => '/storage/productos/66nRKrIqVYpsHj6Fur6khQhDRI9ZUO0PAfYQ2RiE.webp',
                'es_principal' => 1,
                'producto_id' => 43,
            ],
            [
                'id' => 75,
                'url' => '/storage/productos/g2I7yqeDeun2AXa1gM5BSf9CXT7Y37G2xiaLDc8Z.webp',
                'es_principal' => 0,
                'producto_id' => 43,
            ],
            [
                'id' => 76,
                'url' => '/storage/productos/CgWE48KjnMPS1OLN35M3IWBhFd9mahBqh5fMrLJJ.webp',
                'es_principal' => 0,
                'producto_id' => 43,
            ],
            [
                'id' => 77,
                'url' => '/storage/productos/C79pZa2Yge64WjS8W3UlO3gT5JY0VmvBx3eNWqBE.webp',
                'es_principal' => 0,
                'producto_id' => 43,
            ],
            [
                'id' => 78,
                'url' => '/storage/productos/SENbB3IEaK2hDIj847ifwvkgKGjeNBtWKDdBo7pM.webp',
                'es_principal' => 1,
                'producto_id' => 44,
            ],
            [
                'id' => 79,
                'url' => '/storage/productos/3KSESsT3PpCxsX30nlEVrnk32AnqB7n6gxif38Dk.webp',
                'es_principal' => 0,
                'producto_id' => 44,
            ],
            [
                'id' => 80,
                'url' => '/storage/productos/c92bHUMjgeyBOXHVkx30YlnZ9fqCepyMddVSP82m.webp',
                'es_principal' => 0,
                'producto_id' => 44,
            ],
            [
                'id' => 81,
                'url' => '/storage/productos/N57jSKxPCJaEAnLydHGlcnJ0Vh58hi0mhKmAWGzy.webp',
                'es_principal' => 1,
                'producto_id' => 45,
            ],
            [
                'id' => 82,
                'url' => '/storage/productos/Jer5PTYPUtvvOtsk9LKaKf5ekUF5uNHClnd4Xjpb.webp',
                'es_principal' => 0,
                'producto_id' => 45,
            ],
            [
                'id' => 83,
                'url' => '/storage/productos/GmbsRc8NpO1mNTlhKNTrKIPAJtpmbkuKlCQyhjSu.webp',
                'es_principal' => 1,
                'producto_id' => 46,
            ],
            [
                'id' => 84,
                'url' => '/storage/productos/kv8ADZVKyKul0g3Ev07w8ZPYFnL8H4VbACJ8j6un.webp',
                'es_principal' => 0,
                'producto_id' => 46,
            ],
            [
                'id' => 85,
                'url' => '/storage/productos/m1NdbzckPvTPitkLnCHjqFcsMMCoNqg8T537GWkr.webp',
                'es_principal' => 1,
                'producto_id' => 47,
            ],
            [
                'id' => 86,
                'url' => '/storage/productos/zvm8miXJw0ZZ3wbs707t5h45mBOHOqw1TdpSyaoD.webp',
                'es_principal' => 0,
                'producto_id' => 47,
            ],
            [
                'id' => 87,
                'url' => '/storage/productos/yaCjnUOilbueJzaXusxD3FgrnpjwDgAyY7J7MhiJ.webp',
                'es_principal' => 1,
                'producto_id' => 48,
            ],
            [
                'id' => 88,
                'url' => '/storage/productos/348ZnwXzPhVNRWGUAD4U8FzbBErGWDzwrlkNcxOo.webp',
                'es_principal' => 1,
                'producto_id' => 49,
            ],
            [
                'id' => 89,
                'url' => '/storage/productos/yne1uzAQiyMHFNBRRIvJStjBSE4JmlEhAvE1WMln.webp',
                'es_principal' => 1,
                'producto_id' => 50,
            ],
            [
                'id' => 90,
                'url' => '/storage/productos/lcuPuYsE1BqphVUvdkecF2OG2kMsOnKuJjZsfV2n.webp',
                'es_principal' => 0,
                'producto_id' => 50,
            ],
            [
                'id' => 91,
                'url' => '/storage/productos/nCTvzP3wfJJxO85XxPGIPwjkJeUxFpj6i7ECNMvF.webp',
                'es_principal' => 1,
                'producto_id' => 51,
            ],
            [
                'id' => 92,
                'url' => '/storage/productos/LAX85nbTgES5aQaGOZs0sSnViIEAsOqoSh9T6Qpc.webp',
                'es_principal' => 0,
                'producto_id' => 51,
            ],
            [
                'id' => 93,
                'url' => '/storage/productos/pvCGQwR7nWvGauak533HZuJHmkB01tANb7k1FBhx.webp',
                'es_principal' => 0,
                'producto_id' => 51,
            ],
            [
                'id' => 94,
                'url' => '/storage/productos/MAm1LTA4ePnhwnpgf6ecG7RQ5ok5kBdGm4ZuWqKI.webp',
                'es_principal' => 0,
                'producto_id' => 51,
            ],
            [
                'id' => 97,
                'url' => '/storage/productos/NfYTtFrCfzQvv7UdmAxKFjfkpjN3fqNLHnZX2FrK.webp',
                'es_principal' => 1,
                'producto_id' => 53,
            ],
            [
                'id' => 98,
                'url' => '/storage/productos/ZeXIhiuiiMNV65Eq5V5rH0tdgjm7EUnqSzHFzI3B.webp',
                'es_principal' => 0,
                'producto_id' => 53,
            ],
        ]);
    }
}