<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductoSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('productos')->insertOrIgnore([
            [
                'id' => 7,
                'nombre' => 'Enrique IV a las puertas de París (agosto 1590)',
                'descripcion' => 'Grabado antiguo original (litografía), Imprenta de Bougeard, Francia, Mediados del siglo XIX',
                'precio' => 45.00,
                'estado' => 'disponible',
                'destacado' => 0,
                'permite_reserva' => 1,
                'permite_alquiler' => 1,
                'subcategoria_id' => 18,
                'pais_id' => 2,
                'epoca_id' => 3,
                'medidas' => null,
                'materiales' => null,
            ],
            [
                'id' => 8,
                'nombre' => 'La France illustrée',
                'descripcion' => 'Grabado antiguo original coloreado a mano, La Rochèle (Charente maritime), Francia, Grabado de la obra de V.A. Nakte Brun, Paris 1855',
                'precio' => 50.00,
                'estado' => 'disponible',
                'destacado' => 1,
                'permite_reserva' => 1,
                'permite_alquiler' => 1,
                'subcategoria_id' => 18,
                'pais_id' => 2,
                'epoca_id' => 3,
                'medidas' => null,
                'materiales' => null,
            ],
            [
                'id' => 9,
                'nombre' => 'Trineo Ruso (finales siglo XIX)',
                'descripcion' => 'Trineo de 4 plazas + cochero. Asientos cubiertos por pieles de lobo',
                'precio' => 0.00,
                'estado' => 'disponible',
                'destacado' => 1,
                'permite_reserva' => 1,
                'permite_alquiler' => 1,
                'subcategoria_id' => 5,
                'pais_id' => 4,
                'epoca_id' => 3,
                'medidas' => null,
                'materiales' => null,
            ],
            [
                'id' => 11,
                'nombre' => 'Vajilla Luneville',
                'descripcion' => 'Cerámica de Luneville (Francia). Modelo "Lucy" (modernista) en torno a 1900. 20 platos, ensaladera, fuente redonda grande, fuente oval grande, fuente pequeña oval, salsera',
                'precio' => 270.00,
                'estado' => 'disponible',
                'destacado' => 1,
                'permite_reserva' => 1,
                'permite_alquiler' => 0,
                'subcategoria_id' => 12,
                'pais_id' => 2,
                'epoca_id' => 3,
                'medidas' => null,
                'materiales' => 'Cerámica',
            ],
            [
                'id' => 12,
                'nombre' => 'Instrumental de Ministrante',
                'descripcion' => "Instrumental de ministrante (\"practicante - sangrandor\"). Mediados del siglo XIX.\nLas actuaciones de un ministrante eran las siguientes: evacuaciones sanguíneas generales y tópicas (sangrías), contención de flujos de sangre en accidentes, aplicación a la piel de medicamentos y ventosas, vendajes más frecuentes en medicina, inyección de sustancias medicamentosas por vías naturales, limpieza de dentadura y extracción de dientes y muelas",
                'precio' => 350.00,
                'estado' => 'disponible',
                'destacado' => 0,
                'permite_reserva' => 1,
                'permite_alquiler' => 0,
                'subcategoria_id' => 25,
                'pais_id' => 2,
                'epoca_id' => 3,
                'medidas' => null,
                'materiales' => null,
            ],
            [
                'id' => 13,
                'nombre' => 'Candelabro',
                'descripcion' => 'Candelabro dorado y verde',
                'precio' => 1200.00,
                'estado' => 'disponible',
                'destacado' => 0,
                'permite_reserva' => 1,
                'permite_alquiler' => 1,
                'subcategoria_id' => 11,
                'pais_id' => 1,
                'epoca_id' => 1,
                'medidas' => null,
                'materiales' => null,
            ],
            [
                'id' => 14,
                'nombre' => 'Armadura',
                'descripcion' => 'Armadura de hierro',
                'precio' => 0.00,
                'estado' => 'disponible',
                'destacado' => 0,
                'permite_reserva' => 1,
                'permite_alquiler' => 1,
                'subcategoria_id' => 26,
                'pais_id' => 1,
                'epoca_id' => 1,
                'medidas' => null,
                'materiales' => null,
            ],
            [
                'id' => 15,
                'nombre' => 'Armario vajillero',
                'descripcion' => 'Armario de madera con vajillero',
                'precio' => 0.00,
                'estado' => 'disponible',
                'destacado' => 0,
                'permite_reserva' => 1,
                'permite_alquiler' => 1,
                'subcategoria_id' => 3,
                'pais_id' => 1,
                'epoca_id' => 1,
                'medidas' => null,
                'materiales' => null,
            ],
            [
                'id' => 16,
                'nombre' => 'Armario rústico',
                'descripcion' => 'Armario',
                'precio' => 0.00,
                'estado' => 'disponible',
                'destacado' => 0,
                'permite_reserva' => 1,
                'permite_alquiler' => 1,
                'subcategoria_id' => 3,
                'pais_id' => 1,
                'epoca_id' => 1,
                'medidas' => null,
                'materiales' => null,
            ],
            [
                'id' => 17,
                'nombre' => 'Botellas de cristal',
                'descripcion' => 'Varias botella de cristal',
                'precio' => 0.00,
                'estado' => 'disponible',
                'destacado' => 0,
                'permite_reserva' => 1,
                'permite_alquiler' => 1,
                'subcategoria_id' => 27,
                'pais_id' => 1,
                'epoca_id' => 1,
                'medidas' => null,
                'materiales' => null,
            ],
            [
                'id' => 18,
                'nombre' => 'Cuadro con calavera',
                'descripcion' => 'madera con calavera de ciervo',
                'precio' => 110.00,
                'estado' => 'disponible',
                'destacado' => 0,
                'permite_reserva' => 1,
                'permite_alquiler' => 1,
                'subcategoria_id' => 28,
                'pais_id' => 1,
                'epoca_id' => 1,
                'medidas' => null,
                'materiales' => null,
            ],
            [
                'id' => 19,
                'nombre' => 'Pintura al oleo',
                'descripcion' => 'Cuadro pintura',
                'precio' => 130.00,
                'estado' => 'disponible',
                'destacado' => 0,
                'permite_reserva' => 1,
                'permite_alquiler' => 1,
                'subcategoria_id' => 17,
                'pais_id' => 1,
                'epoca_id' => 1,
                'medidas' => null,
                'materiales' => null,
            ],
            [
                'id' => 20,
                'nombre' => 'Camara antigua',
                'descripcion' => 'Cuadro de fuelle (?)',
                'precio' => 250.00,
                'estado' => 'disponible',
                'destacado' => 0,
                'permite_reserva' => 1,
                'permite_alquiler' => 1,
                'subcategoria_id' => 29,
                'pais_id' => 1,
                'epoca_id' => 1,
                'medidas' => null,
                'materiales' => null,
            ],
            [
                'id' => 21,
                'nombre' => 'Candelabro dorado',
                'descripcion' => 'Candelabro con figura dorada',
                'precio' => 0.00,
                'estado' => 'disponible',
                'destacado' => 0,
                'permite_reserva' => 1,
                'permite_alquiler' => 1,
                'subcategoria_id' => 11,
                'pais_id' => 1,
                'epoca_id' => 1,
                'medidas' => null,
                'materiales' => null,
            ],
            [
                'id' => 22,
                'nombre' => 'Candelabro',
                'descripcion' => 'Candelabro con joyas',
                'precio' => 0.00,
                'estado' => 'disponible',
                'destacado' => 0,
                'permite_reserva' => 1,
                'permite_alquiler' => 1,
                'subcategoria_id' => 11,
                'pais_id' => 1,
                'epoca_id' => 1,
                'medidas' => null,
                'materiales' => null,
            ],
            [
                'id' => 23,
                'nombre' => 'Candelabro de pared',
                'descripcion' => 'Candelabro de pared simple',
                'precio' => 0.00,
                'estado' => 'disponible',
                'destacado' => 0,
                'permite_reserva' => 1,
                'permite_alquiler' => 1,
                'subcategoria_id' => 11,
                'pais_id' => 1,
                'epoca_id' => 1,
                'medidas' => null,
                'materiales' => null,
            ],
            [
                'id' => 25,
                'nombre' => "L'Etat, c'est moi.",
                'descripcion' => 'Grabado antiguo',
                'precio' => 60.00,
                'estado' => 'disponible',
                'destacado' => 0,
                'permite_reserva' => 1,
                'permite_alquiler' => 1,
                'subcategoria_id' => 18,
                'pais_id' => 1,
                'epoca_id' => 1,
                'medidas' => null,
                'materiales' => null,
            ],
            [
                'id' => 26,
                'nombre' => 'Escritorio',
                'descripcion' => 'Escritorio de madera',
                'precio' => 0.00,
                'estado' => 'disponible',
                'destacado' => 0,
                'permite_reserva' => 1,
                'permite_alquiler' => 1,
                'subcategoria_id' => 30,
                'pais_id' => 1,
                'epoca_id' => 1,
                'medidas' => null,
                'materiales' => null,
            ],
            [
                'id' => 27,
                'nombre' => 'Figura de bronce con reloj y trofeos',
                'descripcion' => 'pack de figuras de bronce',
                'precio' => 0.00,
                'estado' => 'disponible',
                'destacado' => 0,
                'permite_reserva' => 1,
                'permite_alquiler' => 1,
                'subcategoria_id' => 16,
                'pais_id' => 1,
                'epoca_id' => 1,
                'medidas' => null,
                'materiales' => null,
            ],
            [
                'id' => 28,
                'nombre' => 'Espejo dorado',
                'descripcion' => 'Espejo dorado',
                'precio' => 350.00,
                'estado' => 'disponible',
                'destacado' => 1,
                'permite_reserva' => 1,
                'permite_alquiler' => 1,
                'subcategoria_id' => 6,
                'pais_id' => 1,
                'epoca_id' => 1,
                'medidas' => null,
                'materiales' => null,
            ],
            [
                'id' => 29,
                'nombre' => 'Espejo de madera',
                'descripcion' => 'Espejo',
                'precio' => 0.00,
                'estado' => 'disponible',
                'destacado' => 0,
                'permite_reserva' => 1,
                'permite_alquiler' => 1,
                'subcategoria_id' => 6,
                'pais_id' => 1,
                'epoca_id' => 1,
                'medidas' => null,
                'materiales' => 'Madera',
            ],
            [
                'id' => 30,
                'nombre' => 'Espejo de madera grande',
                'descripcion' => 'Espejo',
                'precio' => 0.00,
                'estado' => 'disponible',
                'destacado' => 0,
                'permite_reserva' => 1,
                'permite_alquiler' => 1,
                'subcategoria_id' => 6,
                'pais_id' => 1,
                'epoca_id' => 1,
                'medidas' => null,
                'materiales' => 'Madera',
            ],
            [
                'id' => 31,
                'nombre' => 'Jarrones de cerámica',
                'descripcion' => 'Jarrones',
                'precio' => 0.00,
                'estado' => 'disponible',
                'destacado' => 0,
                'permite_reserva' => 1,
                'permite_alquiler' => 1,
                'subcategoria_id' => 8,
                'pais_id' => 1,
                'epoca_id' => 1,
                'medidas' => null,
                'materiales' => 'Madera',
            ],
            [
                'id' => 32,
                'nombre' => 'Benditera de cerámica',
                'descripcion' => 'Benditera en cerámica verde y azul cobalto, representando un motivo de calvario, con Jesús crucificado, la Virgen y San Juan. Teruel - Valencia. Siglo XVII',
                'precio' => 350.00,
                'estado' => 'disponible',
                'destacado' => 0,
                'permite_reserva' => 1,
                'permite_alquiler' => 0,
                'subcategoria_id' => 31,
                'pais_id' => 1,
                'epoca_id' => 1,
                'medidas' => null,
                'materiales' => 'Cerámica',
            ],
            [
                'id' => 33,
                'nombre' => 'Lámpara de mesa',
                'descripcion' => 'Lámpara de mesa',
                'precio' => 0.00,
                'estado' => 'disponible',
                'destacado' => 0,
                'permite_reserva' => 1,
                'permite_alquiler' => 0,
                'subcategoria_id' => 10,
                'pais_id' => 1,
                'epoca_id' => 1,
                'medidas' => null,
                'materiales' => 'Cerámica',
            ],
            [
                'id' => 34,
                'nombre' => 'Libro antiguo',
                'descripcion' => 'Libro antiguo de medicina',
                'precio' => 0.00,
                'estado' => 'disponible',
                'destacado' => 0,
                'permite_reserva' => 1,
                'permite_alquiler' => 0,
                'subcategoria_id' => 32,
                'pais_id' => 1,
                'epoca_id' => 1,
                'medidas' => null,
                'materiales' => 'Cerámica',
            ],
            [
                'id' => 35,
                'nombre' => 'Mesa',
                'descripcion' => 'Mesa madera',
                'precio' => 0.00,
                'estado' => 'disponible',
                'destacado' => 0,
                'permite_reserva' => 1,
                'permite_alquiler' => 0,
                'subcategoria_id' => 2,
                'pais_id' => 1,
                'epoca_id' => 1,
                'medidas' => null,
                'materiales' => 'Cerámica',
            ],
            [
                'id' => 36,
                'nombre' => 'Mesa 2',
                'descripcion' => 'Mesa madera',
                'precio' => 0.00,
                'estado' => 'disponible',
                'destacado' => 0,
                'permite_reserva' => 1,
                'permite_alquiler' => 0,
                'subcategoria_id' => 2,
                'pais_id' => 1,
                'epoca_id' => 1,
                'medidas' => null,
                'materiales' => 'Cerámica',
            ],
            [
                'id' => 39,
                'nombre' => 'Radio antigua 1',
                'descripcion' => 'radio antigua negra',
                'precio' => 0.00,
                'estado' => 'disponible',
                'destacado' => 0,
                'permite_reserva' => 1,
                'permite_alquiler' => 0,
                'subcategoria_id' => 33,
                'pais_id' => 1,
                'epoca_id' => 1,
                'medidas' => null,
                'materiales' => 'Madera',
            ],
            [
                'id' => 40,
                'nombre' => 'Radio antigua 2',
                'descripcion' => 'radio antigua negra',
                'precio' => 115.00,
                'estado' => 'disponible',
                'destacado' => 0,
                'permite_reserva' => 1,
                'permite_alquiler' => 0,
                'subcategoria_id' => 33,
                'pais_id' => 1,
                'epoca_id' => 1,
                'medidas' => null,
                'materiales' => 'Madera',
            ],
            [
                'id' => 41,
                'nombre' => 'Reloj de madera con pendulo',
                'descripcion' => 'Reloj de madera con pendulo',
                'precio' => 380.00,
                'estado' => 'disponible',
                'destacado' => 0,
                'permite_reserva' => 1,
                'permite_alquiler' => 0,
                'subcategoria_id' => 7,
                'pais_id' => 1,
                'epoca_id' => 1,
                'medidas' => null,
                'materiales' => 'Madera',
            ],
            [
                'id' => 42,
                'nombre' => 'Reloj alto de madera con pendulo',
                'descripcion' => 'Reloj de madera con pendulo',
                'precio' => 0.00,
                'estado' => 'disponible',
                'destacado' => 0,
                'permite_reserva' => 1,
                'permite_alquiler' => 0,
                'subcategoria_id' => 7,
                'pais_id' => 1,
                'epoca_id' => 1,
                'medidas' => null,
                'materiales' => 'Madera',
            ],
            [
                'id' => 43,
                'nombre' => 'Reloj dorado y copas',
                'descripcion' => 'Pack de esculturas doradas reloj y copas',
                'precio' => 0.00,
                'estado' => 'disponible',
                'destacado' => 0,
                'permite_reserva' => 1,
                'permite_alquiler' => 0,
                'subcategoria_id' => 7,
                'pais_id' => 1,
                'epoca_id' => 1,
                'medidas' => null,
                'materiales' => 'Madera',
            ],
            [
                'id' => 44,
                'nombre' => 'Silla tela detalles amarillos',
                'descripcion' => 'Silla tela detalles amarillos',
                'precio' => 0.00,
                'estado' => 'disponible',
                'destacado' => 0,
                'permite_reserva' => 1,
                'permite_alquiler' => 0,
                'subcategoria_id' => 1,
                'pais_id' => 1,
                'epoca_id' => 1,
                'medidas' => null,
                'materiales' => 'Madera',
            ],
            [
                'id' => 45,
                'nombre' => 'Silla tela',
                'descripcion' => 'Silla tela',
                'precio' => 0.00,
                'estado' => 'disponible',
                'destacado' => 0,
                'permite_reserva' => 1,
                'permite_alquiler' => 0,
                'subcategoria_id' => 1,
                'pais_id' => 1,
                'epoca_id' => 1,
                'medidas' => null,
                'materiales' => 'Madera',
            ],
            [
                'id' => 46,
                'nombre' => 'Silla tela',
                'descripcion' => 'Silla tela',
                'precio' => 0.00,
                'estado' => 'disponible',
                'destacado' => 0,
                'permite_reserva' => 1,
                'permite_alquiler' => 0,
                'subcategoria_id' => 1,
                'pais_id' => 1,
                'epoca_id' => 1,
                'medidas' => null,
                'materiales' => 'Madera',
            ],
            [
                'id' => 47,
                'nombre' => 'Carrito',
                'descripcion' => 'Trineo negro',
                'precio' => 0.00,
                'estado' => 'disponible',
                'destacado' => 0,
                'permite_reserva' => 1,
                'permite_alquiler' => 0,
                'subcategoria_id' => 5,
                'pais_id' => 1,
                'epoca_id' => 1,
                'medidas' => null,
                'materiales' => 'Madera',
            ],
            [
                'id' => 48,
                'nombre' => 'Sopera cerámica',
                'descripcion' => 'sopera',
                'precio' => 0.00,
                'estado' => 'disponible',
                'destacado' => 0,
                'permite_reserva' => 1,
                'permite_alquiler' => 0,
                'subcategoria_id' => 35,
                'pais_id' => 1,
                'epoca_id' => 1,
                'medidas' => null,
                'materiales' => 'Cerámica',
            ],
            [
                'id' => 49,
                'nombre' => 'Cómoda',
                'descripcion' => 'Cómoda de madera',
                'precio' => 580.00,
                'estado' => 'disponible',
                'destacado' => 0,
                'permite_reserva' => 1,
                'permite_alquiler' => 0,
                'subcategoria_id' => 4,
                'pais_id' => 1,
                'epoca_id' => 1,
                'medidas' => null,
                'materiales' => 'Madera',
            ],
            [
                'id' => 50,
                'nombre' => 'Licorera',
                'descripcion' => 'Purera-Licorera de palma de caoba con incrustaciones de nácar. Francia, época napoleon III (1850-1870)',
                'precio' => 0.00,
                'estado' => 'disponible',
                'destacado' => 0,
                'permite_reserva' => 1,
                'permite_alquiler' => 0,
                'subcategoria_id' => 23,
                'pais_id' => 2,
                'epoca_id' => 3,
                'medidas' => null,
                'materiales' => 'Palma de caoba y nácar',
            ],
            [
                'id' => 51,
                'nombre' => 'Estereoscopio',
                'descripcion' => 'Estereoscopio antiguo',
                'precio' => 0.00,
                'estado' => 'disponible',
                'destacado' => 0,
                'permite_reserva' => 1,
                'permite_alquiler' => 0,
                'subcategoria_id' => 29,
                'pais_id' => 2,
                'epoca_id' => 3,
                'medidas' => null,
                'materiales' => null,
            ],
            [
                'id' => 53,
                'nombre' => 'Producto prueba',
                'descripcion' => null,
                'precio' => null,
                'estado' => 'disponible',
                'destacado' => 0,
                'permite_reserva' => 1,
                'permite_alquiler' => 1,
                'subcategoria_id' => 18,
                'pais_id' => 1,
                'epoca_id' => 1,
                'medidas' => null,
                'materiales' => null,
            ],
        ]);
    }
}